ci:
  collect:
    staticDistDir: "./dist"
    numberOfRuns: 3
  assert:
    preset: "lighthouse:recommended"
    assertions:
      "categories:performance":
        - error
        - minScore: 0.8
      "categories:accessibility":
        - error
        - minScore: 0.95
      "categories:best-practices":
        - error
        - minScore: 0.9
      "categories:seo":
        - error
        - minScore: 0.9
      "unused-css-rules": "off"
      "network-dependency-tree-insight": "off"
      "label-content-name-mismatch": "warn"
